spring:
  datasource:
    username: root
    password: 86450328hzm
    url: jdbc:mysql://localhost:3306/atguigu-springboot-jdbc?serverTimezone=UTC
  jpa:
    hibernate:
      #     更新或者创建数据表结构
      ddl-auto: update
    #    控制台显示SQL
    show-sql: true
